### ISSUE TITLE
error caused by update of github.com/mholt/archiver 

### ISSUE THREAD

**Issue by hikaru7719** [mackerelio/mkr#176] opened 2018-11-09 05:58 UTC
I ran `go get github.com/mackerelio/mkr` and `go install github.com/mackerelio/mkr`. 
But there was a following error message.

```
$ go get github.com/mackerelio/mkr
# github.com/mackerelio/mkr/plugin
plugin/install.go:215:20: invalid method expression archiver.Zip.Open (needs pointer receiver: (*archiver.Zip).Open)
plugin/install.go:217:22: invalid method expression archiver.TarGz.Open (needs pointer receiver: (*archiver.TarGz).Open)
```
I watched #175 . I think that the cause of error is update of 'github.com/mholt/archiver' too.
(Sorry,I am not good at Ennglish.)

**Comment by astj** [comment] 2018-11-09 09:00
Thank you for reporting. 
You're right, it's caused by change of github.com/mholt/archiver, and should be solved by #175.
Please wait until #175 merged.

**Closed** 2018-11-20 14:15 UTC
